-- schema.sql
-- CS 370 Programming Assignment 1: Authenticate User
-- Minimal schema for user registration and login

USE cs370_section2_cafcode;

CREATE TABLE IF NOT EXISTS User (
	user_id		INT AUTO_INCREMENT PRIMARY KEY,
	user_name	VARCHAR(50) NOT NULL UNIQUE,
	email		VARCHAR(320) NOT NULL UNIQUE,
	password_hash	VARCHAR(255) NOT NULL,
	created		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)	ENGINE=InnoDB;

-- --------------------------------------------------------
-- Table structure for table `Session`
-- --------------------------------------------------------
-- session_id is a 64-char hex token generated by our app
CREATE TABLE IF NOT EXISTS Session (
    session_id   CHAR(64)   PRIMARY KEY,                 -- random hex token for session
    user_id      INT        NOT NULL,                    -- links to User.user_id
    created_at   DATETIME   NOT NULL DEFAULT NOW(),      -- when session created
    last_seen_at DATETIME   NOT NULL DEFAULT NOW(),      -- last page interaction
    CONSTRAINT fk_session_user
        FOREIGN KEY (user_id) REFERENCES `User`(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_session_user ON `Session`(user_id);

-- --------------------------------------------------------
-- Items
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `Items` (
    item_id        INT          AUTO_INCREMENT PRIMARY KEY,
    owner_id       INT          NOT NULL,                      -- FK -> User.user_id
    item_name      VARCHAR(255) NOT NULL,
    category       VARCHAR(64)  NOT NULL,                      -- simple text category
    description    TEXT         NOT NULL,
    posted_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_items_owner
        FOREIGN KEY (owner_id) REFERENCES `User`(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_items_owner  ON `Items`(owner_id);
CREATE INDEX IF NOT EXISTS idx_items_cat    ON `Items`(category);
CREATE INDEX IF NOT EXISTS idx_items_posted ON `Items`(posted_date);

-- --------------------------------------------------------
-- Auctions  (normalized, no cached leader fields)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `Auctions` (
    auction_id   INT           AUTO_INCREMENT PRIMARY KEY,
    item_id      INT           NOT NULL,                       -- FK -> Items.item_id
    start_price  DECIMAL(10,2) NOT NULL,
    start_time   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration     INT           NOT NULL,                       -- minutes
    status       ENUM('scheduled','running','ended','cancelled') NOT NULL DEFAULT 'scheduled',
    CONSTRAINT fk_auctions_item
        FOREIGN KEY (item_id) REFERENCES `Items`(item_id) ON DELETE CASCADE,
    CONSTRAINT chk_auctions_positive
        CHECK (start_price >= 0 AND duration > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_auctions_item   ON `Auctions`(item_id);
CREATE INDEX IF NOT EXISTS idx_auctions_status ON `Auctions`(status);
CREATE INDEX IF NOT EXISTS idx_auctions_time   ON `Auctions`(start_time);

-- --------------------------------------------------------
-- Bids  (history-preserving, each bid gets an id)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bids` (
    bid_id      INT           AUTO_INCREMENT PRIMARY KEY,
    auction_id  INT           NOT NULL,                        -- FK -> Auctions.auction_id
    bidder_id   INT           NOT NULL,                        -- FK -> User.user_id
    bid_amount  DECIMAL(10,2) NOT NULL,
    bid_time    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bids_auction
        FOREIGN KEY (auction_id) REFERENCES `Auctions`(auction_id) ON DELETE CASCADE,
    CONSTRAINT fk_bids_bidder
        FOREIGN KEY (bidder_id)  REFERENCES `User`(user_id)     ON DELETE CASCADE,
    CONSTRAINT chk_bid_amount_positive
        CHECK (bid_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Helpful indexes for typical queries (highest bid, user history)
CREATE INDEX IF NOT EXISTS idx_bids_auction_time ON `Bids`(auction_id, bid_time);
CREATE INDEX IF NOT EXISTS idx_bids_bidder_time  ON `Bids`(bidder_id, bid_time);
CREATE INDEX IF NOT EXISTS idx_bids_amt          ON `Bids`(bid_amount);

